config:
  user.user-data: |
    ssh_pwauth: yes
    users:
      - name: coder
        passwd: $6$cvPx25uaHvVc8z$IYXYZQsey4svKQ6z9oextx5R.13zuQtjZMdIJyBGKK5gTze3VxcJeU05HfHuGOXOI9DbbaJp9Un0jweY1mBv2/
        lock_passwd: false
        groups: lxd
        shell: /bin/bash
        sudo: ALL=(ALL) NOPASSWD:ALL
description: default profile for playground virtual machine instance
devices:
  enp5s0:
      name: enp5s0
      network: lxdbr0
      type: nic
  root:
      path: /
      pool: pool1
      type: disk
  config:
    source: cloud-init:config
    type: disk
name: virtualmachine
